doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        use_savepoints: true

    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    AuthRegisterDomain:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Auth/Register/Domain'
                        prefix: 'App\Auth\Register\Domain'
                        alias: Register
                    AuthLoginDomain:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Auth/Login/Domain'
                        prefix: 'App\Auth\Login\Domain'
                        alias: login
                    SensorCreateDomain:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Sensors/Create/Domain/Entity'
                        prefix: 'App\Sensors\Create\Domain\Entity'
                        alias: create
                    SensorGetAllDomain:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Sensors/GetAll/Domain/Entity'
                        prefix: 'App\Sensors\GetAll\Domain\Entity'
                        alias: getAll
                    MeasurementCreateDomain:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Measurement/Create/Domain/Entity'
                        prefix: 'App\Measurement\Create\Domain\Entity'
                        alias: createMeasurement
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
