nelmio_api_doc:
    documentation:
        info:
            title: 'API Documentation'
            description: 'This is the documentation of your API.'
            version: '1.0.0'
        components:
            securitySchemes:
                bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - bearer: []

        nelmio_api_doc:
            resource: '@NelmioApiDocBundle/Resources/config/routing/swaggerui.yaml'
            prefix: /api/doc

