#Auth
api_user_register:
  path: /api/register
  controller: App\Auth\Register\Infrastructure\Controller\UserController::register
  methods: [POST]

api_user_login:
  path: /api/login
  controller: App\Auth\Login\Infrastructure\Controller\LoginController::login
  methods: [POST]

#Sensors
api_sensor_create:
  path: /api/sensor/create
  controller: App\Sensors\Create\Infrastructure\Controller\CreateSensorController::create
  methods: [POST]

api_sensor_getAll:
  path: /api/sensor/getAll
  controller: App\Sensors\GetAll\Infrastructure\Controller\GetAllSensorController::getAll
  methods: [GET]

#Measurements

api_measurement_create:
  path: /api/measurement/create
  controller: App\Measurement\Create\Infrastructure\Controller\CreateMeasurementController::create
  methods: [POST]

#wines
api_wines_getAll:
  path: /api/wines/getAll
  controller: App\Wines\GetAll\Infrastructure\Controller\WineController::getAll
  methods: [GET]